INSERT INTO continents (name) VALUES ('Africa'), ('Asia'), ('Europe');

INSERT INTO countries (continent_id, name) VALUES
    (1, 'Kenya'),
    (1, 'Nigeria'),
    (2, 'India'),
    (2, 'Japan'),
    (3, 'Germany'),
    (3, 'France');

INSERT INTO counties (country_id, name) VALUES
    (1, 'Nairobi County'),
    (1, 'Mombasa County'),
    (1, 'Kisumu County'),
    (2, 'Lagos State'),
    (2, 'Kano State'),
    (3, 'Maharashtra'),
    (3, 'Karnataka'),
    (4, 'Tokyo'),
    (4, 'Osaka'),
    (5, 'Bavaria'),
    (5, 'Berlin'),
    (6, 'Ile-de-France'),
    (6, 'Provence');

INSERT INTO wards (county_id, name) VALUES
    (1, 'Central Ward'),
    (1, 'Eastleigh Ward'),
    (1, 'Kibera Ward'),
    (2, 'Changamwe Ward'),
    (2, 'Mvita Ward'),
    (3, 'Kisumu Central Ward'),
    (3, 'Mwanza Ward'),
    (4, 'Ikeja Ward'),
    (4, 'Surulere Ward'),
    (5, 'Fagge Ward'),
    (6, 'Andheri Ward'),
    (6, 'Bandra Ward'),
    (7, 'Shinjuku Ward'),
    (7, 'Osaka Ward'),
    (8, 'Munich Ward'),
    (8, 'Nuremberg Ward'),
    (9, 'Paris 1st Ward'),
    (9, 'Marseille Ward');

INSERT INTO villages (ward_id, name) VALUES
    (1, 'Gitanga Village'),
    (1, 'Harambee Village'),
    (2, 'Eastleigh Village'),
    (2, 'Pipeline Village'),
    (3, 'Kibera Village'),
    (3, 'Mukuru Village'),
    (4, 'Changamwe Village'),
    (4, 'Mombasa Old Town'),
    (5, 'Mvita Village'),
    (5, 'Fort Jesus Village'),
    (6, 'Kisumu Town Village'),
    (6, 'Dunga Village'),
    (7, 'Mwanza Village'),
    (8, 'Ikeja Village'),
    (8, 'Ojuelegba Village'),
    (9, 'Surulere Village'),
    (10, 'Fagge Village'),
    (11, 'Andheri Village'),
    (11, 'Bandra Village'),
    (12, 'Shinjuku Village'),
    (12, 'Ikebukuro Village'),
    (13, 'Osaka Village'),
    (14, 'Munich City Village'),
    (14, 'Giesing Village'),
    (15, 'Paris Village'),
    (15, 'Le Marais Village'),
    (16, 'Marseille Village'),
    (16, 'Vieux Port Village');
