TRUNCATE TABLE villages, wards, counties, countries, continents RESTART IDENTITY CASCADE;

-- Continents
INSERT INTO continents (name) VALUES
('Africa'),
('Asia'),
('Europe'),
('North America');

-- Countries
INSERT INTO countries (continent_id, name) VALUES
(1, 'Kenya'),
(1, 'Nigeria'),
(1, 'South Africa'),
(1, 'Ghana'),
(2, 'India'),
(2, 'Japan'),
(2, 'China'),
(2, 'South Korea'),
(3, 'Germany'),
(3, 'France'),
(3, 'Italy'),
(3, 'Spain'),
(4, 'United States'),
(4, 'Canada'),
(4, 'Mexico'),
(4, 'Cuba');

-- Counties
INSERT INTO counties (country_id, name) VALUES
(1, 'Nairobi County'),
(1, 'Mombasa County'),
(1, 'Kisumu County'),
(1, 'Nakuru County'),
(2, 'Lagos Region'),
(2, 'Kano Region'),
(2, 'Abuja Region'),
(2, 'Rivers Region'),
(3, 'Gauteng Region'),
(3, 'Western Cape Region'),
(3, 'KwaZulu Region'),
(3, 'Eastern Cape Region'),
(4, 'Greater Accra Region'),
(4, 'Ashanti Region'),
(4, 'Western Region'),
(4, 'Central Region'),
(5, 'Maharashtra Region'),
(5, 'Karnataka Region'),
(5, 'Gujarat Region'),
(5, 'Punjab Region'),
(6, 'Tokyo Region'),
(6, 'Osaka Region'),
(6, 'Kyoto Region'),
(6, 'Hokkaido Region'),
(7, 'Beijing Region'),
(7, 'Shanghai Region'),
(7, 'Guangdong Region'),
(7, 'Sichuan Region'),
(8, 'Seoul Region'),
(8, 'Busan Region'),
(8, 'Incheon Region'),
(8, 'Daegu Region'),
(9, 'Bavaria Region'),
(9, 'Berlin Region'),
(9, 'Hesse Region'),
(9, 'Saxony Region'),
(10, 'Paris Region'),
(10, 'Lyon Region'),
(10, 'Marseille Region'),
(10, 'Bordeaux Region'),
(11, 'Rome Region'),
(11, 'Milan Region'),
(11, 'Naples Region'),
(11, 'Turin Region'),
(12, 'Madrid Region'),
(12, 'Barcelona Region'),
(12, 'Valencia Region'),
(12, 'Seville Region'),
(13, 'California Region'),
(13, 'Texas Region'),
(13, 'Florida Region'),
(13, 'New York Region'),
(14, 'Ontario Region'),
(14, 'Quebec Region'),
(14, 'Alberta Region'),
(14, 'British Columbia Region'),
(15, 'Mexico City Region'),
(15, 'Jalisco Region'),
(15, 'Nuevo Leon Region'),
(15, 'Yucatan Region'),
(16, 'Havana Region'),
(16, 'Santiago Region'),
(16, 'Camaguey Region'),
(16, 'Holguin Region');

-- Wards
INSERT INTO wards (county_id, name) VALUES
(1, 'Nairobi Central Ward'),
(1, 'Nairobi Harbour Ward'),
(1, 'Nairobi Market Ward'),
(1, 'Nairobi Garden Ward'),
(2, 'Mombasa Highland Ward'),
(2, 'Mombasa Brookside Ward'),
(2, 'Mombasa Meadow Ward'),
(2, 'Mombasa Sunset Ward'),
(3, 'Kisumu Eastgate Ward'),
(3, 'Kisumu Westgate Ward'),
(3, 'Kisumu Northview Ward'),
(3, 'Kisumu Southridge Ward'),
(4, 'Nakuru Riverside Ward'),
(4, 'Nakuru Greenfield Ward'),
(4, 'Nakuru Hillview Ward'),
(4, 'Nakuru Lakeside Ward'),
(5, 'Lagos Central Ward'),
(5, 'Lagos Harbour Ward'),
(5, 'Lagos Market Ward'),
(5, 'Lagos Garden Ward'),
(6, 'Kano Highland Ward'),
(6, 'Kano Brookside Ward'),
(6, 'Kano Meadow Ward'),
(6, 'Kano Sunset Ward'),
(7, 'Abuja Eastgate Ward'),
(7, 'Abuja Westgate Ward'),
(7, 'Abuja Northview Ward'),
(7, 'Abuja Southridge Ward'),
(8, 'Rivers Riverside Ward'),
(8, 'Rivers Greenfield Ward'),
(8, 'Rivers Hillview Ward'),
(8, 'Rivers Lakeside Ward'),
(9, 'Gauteng Central Ward'),
(9, 'Gauteng Harbour Ward'),
(9, 'Gauteng Market Ward'),
(9, 'Gauteng Garden Ward'),
(10, 'Western Cape Highland Ward'),
(10, 'Western Cape Brookside Ward'),
(10, 'Western Cape Meadow Ward'),
(10, 'Western Cape Sunset Ward'),
(11, 'KwaZulu Eastgate Ward'),
(11, 'KwaZulu Westgate Ward'),
(11, 'KwaZulu Northview Ward'),
(11, 'KwaZulu Southridge Ward'),
(12, 'Eastern Cape Riverside Ward'),
(12, 'Eastern Cape Greenfield Ward'),
(12, 'Eastern Cape Hillview Ward'),
(12, 'Eastern Cape Lakeside Ward'),
(13, 'Greater Accra Central Ward'),
(13, 'Greater Accra Harbour Ward'),
(13, 'Greater Accra Market Ward'),
(13, 'Greater Accra Garden Ward'),
(14, 'Ashanti Highland Ward'),
(14, 'Ashanti Brookside Ward'),
(14, 'Ashanti Meadow Ward'),
(14, 'Ashanti Sunset Ward'),
(15, 'Western Eastgate Ward'),
(15, 'Western Westgate Ward'),
(15, 'Western Northview Ward'),
(15, 'Western Southridge Ward'),
(16, 'Central Riverside Ward'),
(16, 'Central Greenfield Ward'),
(16, 'Central Hillview Ward'),
(16, 'Central Lakeside Ward'),
(17, 'Maharashtra Central Ward'),
(17, 'Maharashtra Harbour Ward'),
(17, 'Maharashtra Market Ward'),
(17, 'Maharashtra Garden Ward'),
(18, 'Karnataka Highland Ward'),
(18, 'Karnataka Brookside Ward'),
(18, 'Karnataka Meadow Ward'),
(18, 'Karnataka Sunset Ward'),
(19, 'Gujarat Eastgate Ward'),
(19, 'Gujarat Westgate Ward'),
(19, 'Gujarat Northview Ward'),
(19, 'Gujarat Southridge Ward'),
(20, 'Punjab Riverside Ward'),
(20, 'Punjab Greenfield Ward'),
(20, 'Punjab Hillview Ward'),
(20, 'Punjab Lakeside Ward'),
(21, 'Tokyo Central Ward'),
(21, 'Tokyo Harbour Ward'),
(21, 'Tokyo Market Ward'),
(21, 'Tokyo Garden Ward'),
(22, 'Osaka Highland Ward'),
(22, 'Osaka Brookside Ward'),
(22, 'Osaka Meadow Ward'),
(22, 'Osaka Sunset Ward'),
(23, 'Kyoto Eastgate Ward'),
(23, 'Kyoto Westgate Ward'),
(23, 'Kyoto Northview Ward'),
(23, 'Kyoto Southridge Ward'),
(24, 'Hokkaido Riverside Ward'),
(24, 'Hokkaido Greenfield Ward'),
(24, 'Hokkaido Hillview Ward'),
(24, 'Hokkaido Lakeside Ward'),
(25, 'Beijing Central Ward'),
(25, 'Beijing Harbour Ward'),
(25, 'Beijing Market Ward'),
(25, 'Beijing Garden Ward'),
(26, 'Shanghai Highland Ward'),
(26, 'Shanghai Brookside Ward'),
(26, 'Shanghai Meadow Ward'),
(26, 'Shanghai Sunset Ward'),
(27, 'Guangdong Eastgate Ward'),
(27, 'Guangdong Westgate Ward'),
(27, 'Guangdong Northview Ward'),
(27, 'Guangdong Southridge Ward'),
(28, 'Sichuan Riverside Ward'),
(28, 'Sichuan Greenfield Ward'),
(28, 'Sichuan Hillview Ward'),
(28, 'Sichuan Lakeside Ward'),
(29, 'Seoul Central Ward'),
(29, 'Seoul Harbour Ward'),
(29, 'Seoul Market Ward'),
(29, 'Seoul Garden Ward'),
(30, 'Busan Highland Ward'),
(30, 'Busan Brookside Ward'),
(30, 'Busan Meadow Ward'),
(30, 'Busan Sunset Ward'),
(31, 'Incheon Eastgate Ward'),
(31, 'Incheon Westgate Ward'),
(31, 'Incheon Northview Ward'),
(31, 'Incheon Southridge Ward'),
(32, 'Daegu Riverside Ward'),
(32, 'Daegu Greenfield Ward'),
(32, 'Daegu Hillview Ward'),
(32, 'Daegu Lakeside Ward'),
(33, 'Bavaria Central Ward'),
(33, 'Bavaria Harbour Ward'),
(33, 'Bavaria Market Ward'),
(33, 'Bavaria Garden Ward'),
(34, 'Berlin Highland Ward'),
(34, 'Berlin Brookside Ward'),
(34, 'Berlin Meadow Ward'),
(34, 'Berlin Sunset Ward'),
(35, 'Hesse Eastgate Ward'),
(35, 'Hesse Westgate Ward'),
(35, 'Hesse Northview Ward'),
(35, 'Hesse Southridge Ward'),
(36, 'Saxony Riverside Ward'),
(36, 'Saxony Greenfield Ward'),
(36, 'Saxony Hillview Ward'),
(36, 'Saxony Lakeside Ward'),
(37, 'Paris Central Ward'),
(37, 'Paris Harbour Ward'),
(37, 'Paris Market Ward'),
(37, 'Paris Garden Ward'),
(38, 'Lyon Highland Ward'),
(38, 'Lyon Brookside Ward'),
(38, 'Lyon Meadow Ward'),
(38, 'Lyon Sunset Ward'),
(39, 'Marseille Eastgate Ward'),
(39, 'Marseille Westgate Ward'),
(39, 'Marseille Northview Ward'),
(39, 'Marseille Southridge Ward'),
(40, 'Bordeaux Riverside Ward'),
(40, 'Bordeaux Greenfield Ward'),
(40, 'Bordeaux Hillview Ward'),
(40, 'Bordeaux Lakeside Ward'),
(41, 'Rome Central Ward'),
(41, 'Rome Harbour Ward'),
(41, 'Rome Market Ward'),
(41, 'Rome Garden Ward'),
(42, 'Milan Highland Ward'),
(42, 'Milan Brookside Ward'),
(42, 'Milan Meadow Ward'),
(42, 'Milan Sunset Ward'),
(43, 'Naples Eastgate Ward'),
(43, 'Naples Westgate Ward'),
(43, 'Naples Northview Ward'),
(43, 'Naples Southridge Ward'),
(44, 'Turin Riverside Ward'),
(44, 'Turin Greenfield Ward'),
(44, 'Turin Hillview Ward'),
(44, 'Turin Lakeside Ward'),
(45, 'Madrid Central Ward'),
(45, 'Madrid Harbour Ward'),
(45, 'Madrid Market Ward'),
(45, 'Madrid Garden Ward'),
(46, 'Barcelona Highland Ward'),
(46, 'Barcelona Brookside Ward'),
(46, 'Barcelona Meadow Ward'),
(46, 'Barcelona Sunset Ward'),
(47, 'Valencia Eastgate Ward'),
(47, 'Valencia Westgate Ward'),
(47, 'Valencia Northview Ward'),
(47, 'Valencia Southridge Ward'),
(48, 'Seville Riverside Ward'),
(48, 'Seville Greenfield Ward'),
(48, 'Seville Hillview Ward'),
(48, 'Seville Lakeside Ward'),
(49, 'California Central Ward'),
(49, 'California Harbour Ward'),
(49, 'California Market Ward'),
(49, 'California Garden Ward'),
(50, 'Texas Highland Ward'),
(50, 'Texas Brookside Ward'),
(50, 'Texas Meadow Ward'),
(50, 'Texas Sunset Ward'),
(51, 'Florida Eastgate Ward'),
(51, 'Florida Westgate Ward'),
(51, 'Florida Northview Ward'),
(51, 'Florida Southridge Ward'),
(52, 'New York Riverside Ward'),
(52, 'New York Greenfield Ward'),
(52, 'New York Hillview Ward'),
(52, 'New York Lakeside Ward'),
(53, 'Ontario Central Ward'),
(53, 'Ontario Harbour Ward'),
(53, 'Ontario Market Ward'),
(53, 'Ontario Garden Ward'),
(54, 'Quebec Highland Ward'),
(54, 'Quebec Brookside Ward'),
(54, 'Quebec Meadow Ward'),
(54, 'Quebec Sunset Ward'),
(55, 'Alberta Eastgate Ward'),
(55, 'Alberta Westgate Ward'),
(55, 'Alberta Northview Ward'),
(55, 'Alberta Southridge Ward'),
(56, 'British Columbia Riverside Ward'),
(56, 'British Columbia Greenfield Ward'),
(56, 'British Columbia Hillview Ward'),
(56, 'British Columbia Lakeside Ward'),
(57, 'Mexico City Central Ward'),
(57, 'Mexico City Harbour Ward'),
(57, 'Mexico City Market Ward'),
(57, 'Mexico City Garden Ward'),
(58, 'Jalisco Highland Ward'),
(58, 'Jalisco Brookside Ward'),
(58, 'Jalisco Meadow Ward'),
(58, 'Jalisco Sunset Ward'),
(59, 'Nuevo Leon Eastgate Ward'),
(59, 'Nuevo Leon Westgate Ward'),
(59, 'Nuevo Leon Northview Ward'),
(59, 'Nuevo Leon Southridge Ward'),
(60, 'Yucatan Riverside Ward'),
(60, 'Yucatan Greenfield Ward'),
(60, 'Yucatan Hillview Ward'),
(60, 'Yucatan Lakeside Ward'),
(61, 'Havana Central Ward'),
(61, 'Havana Harbour Ward'),
(61, 'Havana Market Ward'),
(61, 'Havana Garden Ward'),
(62, 'Santiago Highland Ward'),
(62, 'Santiago Brookside Ward'),
(62, 'Santiago Meadow Ward'),
(62, 'Santiago Sunset Ward'),
(63, 'Camaguey Eastgate Ward'),
(63, 'Camaguey Westgate Ward'),
(63, 'Camaguey Northview Ward'),
(63, 'Camaguey Southridge Ward'),
(64, 'Holguin Riverside Ward'),
(64, 'Holguin Greenfield Ward'),
(64, 'Holguin Hillview Ward'),
(64, 'Holguin Lakeside Ward');

-- Villages
INSERT INTO villages (ward_id, name) VALUES
(1, 'Nairobi AmberGrove Village'),
(1, 'Nairobi AmberHeights Village'),
(1, 'Nairobi AmberBrook Village'),
(1, 'Nairobi AmberValley Village'),
(2, 'Nairobi SilverValley Village'),
(2, 'Nairobi SilverFields Village'),
(2, 'Nairobi SilverHaven Village'),
(2, 'Nairobi SilverRidge Village'),
(3, 'Nairobi GoldenRidge Village'),
(3, 'Nairobi GoldenPark Village'),
(3, 'Nairobi GoldenMeadows Village'),
(3, 'Nairobi GoldenPoint Village'),
(4, 'Nairobi EmeraldPoint Village'),
(4, 'Nairobi EmeraldView Village'),
(4, 'Nairobi EmeraldGardens Village'),
(4, 'Nairobi EmeraldCrossing Village'),
(5, 'Mombasa MapleCrossing Village'),
(5, 'Mombasa MapleEstate Village'),
(5, 'Mombasa MapleHeights Village'),
(5, 'Mombasa MapleVillage Village'),
(6, 'Mombasa WillowVillage Village'),
(6, 'Mombasa WillowSprings Village'),
(6, 'Mombasa WillowCreek Village'),
(6, 'Mombasa WillowTerrace Village'),
(7, 'Mombasa CedarTerrace Village'),
(7, 'Mombasa CedarCove Village'),
(7, 'Mombasa CedarWoodlands Village'),
(7, 'Mombasa CedarPlains Village'),
(8, 'Mombasa PinePlains Village'),
(8, 'Mombasa PineOrchard Village'),
(8, 'Mombasa PineVale Village'),
(8, 'Mombasa PineHarbour Village'),
(9, 'Kisumu RiverHarbour Village'),
(9, 'Kisumu RiverGlade Village'),
(9, 'Kisumu RiverDale Village'),
(9, 'Kisumu RiverHeath Village'),
(10, 'Kisumu SunnyHeath Village'),
(10, 'Kisumu SunnyLanding Village'),
(10, 'Kisumu SunnyCourt Village'),
(10, 'Kisumu SunnyBay Village'),
(11, 'Kisumu SpringBay Village'),
(11, 'Kisumu SpringGrove Village'),
(11, 'Kisumu SpringHeights Village'),
(11, 'Kisumu SpringBrook Village'),
(12, 'Kisumu OakBrook Village'),
(12, 'Kisumu OakValley Village'),
(12, 'Kisumu OakFields Village'),
(12, 'Kisumu OakHaven Village'),
(13, 'Nakuru PalmHaven Village'),
(13, 'Nakuru PalmRidge Village'),
(13, 'Nakuru PalmPark Village'),
(13, 'Nakuru PalmMeadows Village'),
(14, 'Nakuru RoseMeadows Village'),
(14, 'Nakuru RosePoint Village'),
(14, 'Nakuru RoseView Village'),
(14, 'Nakuru RoseGardens Village'),
(15, 'Nakuru CloverGardens Village'),
(15, 'Nakuru CloverCrossing Village'),
(15, 'Nakuru CloverEstate Village'),
(15, 'Nakuru CloverHeights Village'),
(16, 'Nakuru MeadowHeights Village'),
(16, 'Nakuru MeadowVillage Village'),
(16, 'Nakuru MeadowSprings Village'),
(16, 'Nakuru MeadowCreek Village'),
(17, 'Lagos CrystalCreek Village'),
(17, 'Lagos CrystalTerrace Village'),
(17, 'Lagos CrystalCove Village'),
(17, 'Lagos CrystalWoodlands Village'),
(18, 'Lagos HarmonyWoodlands Village'),
(18, 'Lagos HarmonyPlains Village'),
(18, 'Lagos HarmonyOrchard Village'),
(18, 'Lagos HarmonyVale Village'),
(19, 'Lagos BrightVale Village'),
(19, 'Lagos BrightHarbour Village'),
(19, 'Lagos BrightGlade Village'),
(19, 'Lagos BrightDale Village'),
(20, 'Lagos MistyDale Village'),
(20, 'Lagos MistyHeath Village'),
(20, 'Lagos MistyLanding Village'),
(20, 'Lagos MistyCourt Village'),
(21, 'Kano LakeCourt Village'),
(21, 'Kano LakeBay Village'),
(21, 'Kano LakeGrove Village'),
(21, 'Kano LakeHeights Village'),
(22, 'Kano HillHeights Village'),
(22, 'Kano HillBrook Village'),
(22, 'Kano HillValley Village'),
(22, 'Kano HillFields Village'),
(23, 'Kano ForestFields Village'),
(23, 'Kano ForestHaven Village'),
(23, 'Kano ForestRidge Village'),
(23, 'Kano ForestPark Village'),
(24, 'Kano GardenPark Village'),
(24, 'Kano GardenMeadows Village'),
(24, 'Kano GardenPoint Village'),
(24, 'Kano GardenView Village'),
(25, 'Abuja BlueView Village'),
(25, 'Abuja BlueGardens Village'),
(25, 'Abuja BlueCrossing Village'),
(25, 'Abuja BlueEstate Village'),
(26, 'Abuja GreenEstate Village'),
(26, 'Abuja GreenHeights Village'),
(26, 'Abuja GreenVillage Village'),
(26, 'Abuja GreenSprings Village'),
(27, 'Abuja RedSprings Village'),
(27, 'Abuja RedCreek Village'),
(27, 'Abuja RedTerrace Village'),
(27, 'Abuja RedCove Village'),
(28, 'Abuja SapphireCove Village'),
(28, 'Abuja SapphireWoodlands Village'),
(28, 'Abuja SapphirePlains Village'),
(28, 'Abuja SapphireOrchard Village'),
(29, 'Rivers JadeOrchard Village'),
(29, 'Rivers JadeVale Village'),
(29, 'Rivers JadeHarbour Village'),
(29, 'Rivers JadeGlade Village'),
(30, 'Rivers CoralGlade Village'),
(30, 'Rivers CoralDale Village'),
(30, 'Rivers CoralHeath Village'),
(30, 'Rivers CoralLanding Village'),
(31, 'Rivers MorningLanding Village'),
(31, 'Rivers MorningCourt Village'),
(31, 'Rivers MorningBay Village'),
(31, 'Rivers MorningGrove Village'),
(32, 'Rivers GoldenleafGrove Village'),
(32, 'Rivers GoldenleafHeights Village'),
(32, 'Rivers GoldenleafBrook Village'),
(32, 'Rivers GoldenleafValley Village'),
(33, 'Gauteng AmberValley Village'),
(33, 'Gauteng AmberFields Village'),
(33, 'Gauteng AmberHaven Village'),
(33, 'Gauteng AmberRidge Village'),
(34, 'Gauteng SilverRidge Village'),
(34, 'Gauteng SilverPark Village'),
(34, 'Gauteng SilverMeadows Village'),
(34, 'Gauteng SilverPoint Village'),
(35, 'Gauteng GoldenPoint Village'),
(35, 'Gauteng GoldenView Village'),
(35, 'Gauteng GoldenGardens Village'),
(35, 'Gauteng GoldenCrossing Village'),
(36, 'Gauteng EmeraldCrossing Village'),
(36, 'Gauteng EmeraldEstate Village'),
(36, 'Gauteng EmeraldHeights Village'),
(36, 'Gauteng EmeraldVillage Village'),
(37, 'Western Cape MapleVillage Village'),
(37, 'Western Cape MapleSprings Village'),
(37, 'Western Cape MapleCreek Village'),
(37, 'Western Cape MapleTerrace Village'),
(38, 'Western Cape WillowTerrace Village'),
(38, 'Western Cape WillowCove Village'),
(38, 'Western Cape WillowWoodlands Village'),
(38, 'Western Cape WillowPlains Village'),
(39, 'Western Cape CedarPlains Village'),
(39, 'Western Cape CedarOrchard Village'),
(39, 'Western Cape CedarVale Village'),
(39, 'Western Cape CedarHarbour Village'),
(40, 'Western Cape PineHarbour Village'),
(40, 'Western Cape PineGlade Village'),
(40, 'Western Cape PineDale Village'),
(40, 'Western Cape PineHeath Village'),
(41, 'KwaZulu RiverHeath Village'),
(41, 'KwaZulu RiverLanding Village'),
(41, 'KwaZulu RiverCourt Village'),
(41, 'KwaZulu RiverBay Village'),
(42, 'KwaZulu SunnyBay Village'),
(42, 'KwaZulu SunnyGrove Village'),
(42, 'KwaZulu SunnyHeights Village'),
(42, 'KwaZulu SunnyBrook Village'),
(43, 'KwaZulu SpringBrook Village'),
(43, 'KwaZulu SpringValley Village'),
(43, 'KwaZulu SpringFields Village'),
(43, 'KwaZulu SpringHaven Village'),
(44, 'KwaZulu OakHaven Village'),
(44, 'KwaZulu OakRidge Village'),
(44, 'KwaZulu OakPark Village'),
(44, 'KwaZulu OakMeadows Village'),
(45, 'Eastern Cape PalmMeadows Village'),
(45, 'Eastern Cape PalmPoint Village'),
(45, 'Eastern Cape PalmView Village'),
(45, 'Eastern Cape PalmGardens Village'),
(46, 'Eastern Cape RoseGardens Village'),
(46, 'Eastern Cape RoseCrossing Village'),
(46, 'Eastern Cape RoseEstate Village'),
(46, 'Eastern Cape RoseHeights Village'),
(47, 'Eastern Cape CloverHeights Village'),
(47, 'Eastern Cape CloverVillage Village'),
(47, 'Eastern Cape CloverSprings Village'),
(47, 'Eastern Cape CloverCreek Village'),
(48, 'Eastern Cape MeadowCreek Village'),
(48, 'Eastern Cape MeadowTerrace Village'),
(48, 'Eastern Cape MeadowCove Village'),
(48, 'Eastern Cape MeadowWoodlands Village'),
(49, 'Greater Accra CrystalWoodlands Village'),
(49, 'Greater Accra CrystalPlains Village'),
(49, 'Greater Accra CrystalOrchard Village'),
(49, 'Greater Accra CrystalVale Village'),
(50, 'Greater Accra HarmonyVale Village'),
(50, 'Greater Accra HarmonyHarbour Village'),
(50, 'Greater Accra HarmonyGlade Village'),
(50, 'Greater Accra HarmonyDale Village'),
(51, 'Greater Accra BrightDale Village'),
(51, 'Greater Accra BrightHeath Village'),
(51, 'Greater Accra BrightLanding Village'),
(51, 'Greater Accra BrightCourt Village'),
(52, 'Greater Accra MistyCourt Village'),
(52, 'Greater Accra MistyBay Village'),
(52, 'Greater Accra MistyGrove Village'),
(52, 'Greater Accra MistyHeights Village'),
(53, 'Ashanti LakeHeights Village'),
(53, 'Ashanti LakeBrook Village'),
(53, 'Ashanti LakeValley Village'),
(53, 'Ashanti LakeFields Village'),
(54, 'Ashanti HillFields Village'),
(54, 'Ashanti HillHaven Village'),
(54, 'Ashanti HillRidge Village'),
(54, 'Ashanti HillPark Village'),
(55, 'Ashanti ForestPark Village'),
(55, 'Ashanti ForestMeadows Village'),
(55, 'Ashanti ForestPoint Village'),
(55, 'Ashanti ForestView Village'),
(56, 'Ashanti GardenView Village'),
(56, 'Ashanti GardenGardens Village'),
(56, 'Ashanti GardenCrossing Village'),
(56, 'Ashanti GardenEstate Village'),
(57, 'Western BlueEstate Village'),
(57, 'Western BlueHeights Village'),
(57, 'Western BlueVillage Village'),
(57, 'Western BlueSprings Village'),
(58, 'Western GreenSprings Village'),
(58, 'Western GreenCreek Village'),
(58, 'Western GreenTerrace Village'),
(58, 'Western GreenCove Village'),
(59, 'Western RedCove Village'),
(59, 'Western RedWoodlands Village'),
(59, 'Western RedPlains Village'),
(59, 'Western RedOrchard Village'),
(60, 'Western SapphireOrchard Village'),
(60, 'Western SapphireVale Village'),
(60, 'Western SapphireHarbour Village'),
(60, 'Western SapphireGlade Village'),
(61, 'Central JadeGlade Village'),
(61, 'Central JadeDale Village'),
(61, 'Central JadeHeath Village'),
(61, 'Central JadeLanding Village'),
(62, 'Central CoralLanding Village'),
(62, 'Central CoralCourt Village'),
(62, 'Central CoralBay Village'),
(62, 'Central CoralGrove Village'),
(63, 'Central MorningGrove Village'),
(63, 'Central MorningHeights Village'),
(63, 'Central MorningBrook Village'),
(63, 'Central MorningValley Village'),
(64, 'Central GoldenleafValley Village'),
(64, 'Central GoldenleafFields Village'),
(64, 'Central GoldenleafHaven Village'),
(64, 'Central GoldenleafRidge Village'),
(65, 'Maharashtra AmberRidge Village'),
(65, 'Maharashtra AmberPark Village'),
(65, 'Maharashtra AmberMeadows Village'),
(65, 'Maharashtra AmberPoint Village'),
(66, 'Maharashtra SilverPoint Village'),
(66, 'Maharashtra SilverView Village'),
(66, 'Maharashtra SilverGardens Village'),
(66, 'Maharashtra SilverCrossing Village'),
(67, 'Maharashtra GoldenCrossing Village'),
(67, 'Maharashtra GoldenEstate Village'),
(67, 'Maharashtra GoldenHeights Village'),
(67, 'Maharashtra GoldenVillage Village'),
(68, 'Maharashtra EmeraldVillage Village'),
(68, 'Maharashtra EmeraldSprings Village'),
(68, 'Maharashtra EmeraldCreek Village'),
(68, 'Maharashtra EmeraldTerrace Village'),
(69, 'Karnataka MapleTerrace Village'),
(69, 'Karnataka MapleCove Village'),
(69, 'Karnataka MapleWoodlands Village'),
(69, 'Karnataka MaplePlains Village'),
(70, 'Karnataka WillowPlains Village'),
(70, 'Karnataka WillowOrchard Village'),
(70, 'Karnataka WillowVale Village'),
(70, 'Karnataka WillowHarbour Village'),
(71, 'Karnataka CedarHarbour Village'),
(71, 'Karnataka CedarGlade Village'),
(71, 'Karnataka CedarDale Village'),
(71, 'Karnataka CedarHeath Village'),
(72, 'Karnataka PineHeath Village'),
(72, 'Karnataka PineLanding Village'),
(72, 'Karnataka PineCourt Village'),
(72, 'Karnataka PineBay Village'),
(73, 'Gujarat RiverBay Village'),
(73, 'Gujarat RiverGrove Village'),
(73, 'Gujarat RiverHeights Village'),
(73, 'Gujarat RiverBrook Village'),
(74, 'Gujarat SunnyBrook Village'),
(74, 'Gujarat SunnyValley Village'),
(74, 'Gujarat SunnyFields Village'),
(74, 'Gujarat SunnyHaven Village'),
(75, 'Gujarat SpringHaven Village'),
(75, 'Gujarat SpringRidge Village'),
(75, 'Gujarat SpringPark Village'),
(75, 'Gujarat SpringMeadows Village'),
(76, 'Gujarat OakMeadows Village'),
(76, 'Gujarat OakPoint Village'),
(76, 'Gujarat OakView Village'),
(76, 'Gujarat OakGardens Village'),
(77, 'Punjab PalmGardens Village'),
(77, 'Punjab PalmCrossing Village'),
(77, 'Punjab PalmEstate Village'),
(77, 'Punjab PalmHeights Village'),
(78, 'Punjab RoseHeights Village'),
(78, 'Punjab RoseVillage Village'),
(78, 'Punjab RoseSprings Village'),
(78, 'Punjab RoseCreek Village'),
(79, 'Punjab CloverCreek Village'),
(79, 'Punjab CloverTerrace Village'),
(79, 'Punjab CloverCove Village'),
(79, 'Punjab CloverWoodlands Village'),
(80, 'Punjab MeadowWoodlands Village'),
(80, 'Punjab MeadowPlains Village'),
(80, 'Punjab MeadowOrchard Village'),
(80, 'Punjab MeadowVale Village'),
(81, 'Tokyo CrystalVale Village'),
(81, 'Tokyo CrystalHarbour Village'),
(81, 'Tokyo CrystalGlade Village'),
(81, 'Tokyo CrystalDale Village'),
(82, 'Tokyo HarmonyDale Village'),
(82, 'Tokyo HarmonyHeath Village'),
(82, 'Tokyo HarmonyLanding Village'),
(82, 'Tokyo HarmonyCourt Village'),
(83, 'Tokyo BrightCourt Village'),
(83, 'Tokyo BrightBay Village'),
(83, 'Tokyo BrightGrove Village'),
(83, 'Tokyo BrightHeights Village'),
(84, 'Tokyo MistyHeights Village'),
(84, 'Tokyo MistyBrook Village'),
(84, 'Tokyo MistyValley Village'),
(84, 'Tokyo MistyFields Village'),
(85, 'Osaka LakeFields Village'),
(85, 'Osaka LakeHaven Village'),
(85, 'Osaka LakeRidge Village'),
(85, 'Osaka LakePark Village'),
(86, 'Osaka HillPark Village'),
(86, 'Osaka HillMeadows Village'),
(86, 'Osaka HillPoint Village'),
(86, 'Osaka HillView Village'),
(87, 'Osaka ForestView Village'),
(87, 'Osaka ForestGardens Village'),
(87, 'Osaka ForestCrossing Village'),
(87, 'Osaka ForestEstate Village'),
(88, 'Osaka GardenEstate Village'),
(88, 'Osaka GardenHeights Village'),
(88, 'Osaka GardenVillage Village'),
(88, 'Osaka GardenSprings Village'),
(89, 'Kyoto BlueSprings Village'),
(89, 'Kyoto BlueCreek Village'),
(89, 'Kyoto BlueTerrace Village'),
(89, 'Kyoto BlueCove Village'),
(90, 'Kyoto GreenCove Village'),
(90, 'Kyoto GreenWoodlands Village'),
(90, 'Kyoto GreenPlains Village'),
(90, 'Kyoto GreenOrchard Village'),
(91, 'Kyoto RedOrchard Village'),
(91, 'Kyoto RedVale Village'),
(91, 'Kyoto RedHarbour Village'),
(91, 'Kyoto RedGlade Village'),
(92, 'Kyoto SapphireGlade Village'),
(92, 'Kyoto SapphireDale Village'),
(92, 'Kyoto SapphireHeath Village'),
(92, 'Kyoto SapphireLanding Village'),
(93, 'Hokkaido JadeLanding Village'),
(93, 'Hokkaido JadeCourt Village'),
(93, 'Hokkaido JadeBay Village'),
(93, 'Hokkaido JadeGrove Village'),
(94, 'Hokkaido CoralGrove Village'),
(94, 'Hokkaido CoralHeights Village'),
(94, 'Hokkaido CoralBrook Village'),
(94, 'Hokkaido CoralValley Village'),
(95, 'Hokkaido MorningValley Village'),
(95, 'Hokkaido MorningFields Village'),
(95, 'Hokkaido MorningHaven Village'),
(95, 'Hokkaido MorningRidge Village'),
(96, 'Hokkaido GoldenleafRidge Village'),
(96, 'Hokkaido GoldenleafPark Village'),
(96, 'Hokkaido GoldenleafMeadows Village'),
(96, 'Hokkaido GoldenleafPoint Village'),
(97, 'Beijing AmberPoint Village'),
(97, 'Beijing AmberView Village'),
(97, 'Beijing AmberGardens Village'),
(97, 'Beijing AmberCrossing Village'),
(98, 'Beijing SilverCrossing Village'),
(98, 'Beijing SilverEstate Village'),
(98, 'Beijing SilverHeights Village'),
(98, 'Beijing SilverVillage Village'),
(99, 'Beijing GoldenVillage Village'),
(99, 'Beijing GoldenSprings Village'),
(99, 'Beijing GoldenCreek Village'),
(99, 'Beijing GoldenTerrace Village'),
(100, 'Beijing EmeraldTerrace Village'),
(100, 'Beijing EmeraldCove Village'),
(100, 'Beijing EmeraldWoodlands Village'),
(100, 'Beijing EmeraldPlains Village'),
(101, 'Shanghai MaplePlains Village'),
(101, 'Shanghai MapleOrchard Village'),
(101, 'Shanghai MapleVale Village'),
(101, 'Shanghai MapleHarbour Village'),
(102, 'Shanghai WillowHarbour Village'),
(102, 'Shanghai WillowGlade Village'),
(102, 'Shanghai WillowDale Village'),
(102, 'Shanghai WillowHeath Village'),
(103, 'Shanghai CedarHeath Village'),
(103, 'Shanghai CedarLanding Village'),
(103, 'Shanghai CedarCourt Village'),
(103, 'Shanghai CedarBay Village'),
(104, 'Shanghai PineBay Village'),
(104, 'Shanghai PineGrove Village'),
(104, 'Shanghai PineHeights Village'),
(104, 'Shanghai PineBrook Village'),
(105, 'Guangdong RiverBrook Village'),
(105, 'Guangdong RiverValley Village'),
(105, 'Guangdong RiverFields Village'),
(105, 'Guangdong RiverHaven Village'),
(106, 'Guangdong SunnyHaven Village'),
(106, 'Guangdong SunnyRidge Village'),
(106, 'Guangdong SunnyPark Village'),
(106, 'Guangdong SunnyMeadows Village'),
(107, 'Guangdong SpringMeadows Village'),
(107, 'Guangdong SpringPoint Village'),
(107, 'Guangdong SpringView Village'),
(107, 'Guangdong SpringGardens Village'),
(108, 'Guangdong OakGardens Village'),
(108, 'Guangdong OakCrossing Village'),
(108, 'Guangdong OakEstate Village'),
(108, 'Guangdong OakHeights Village'),
(109, 'Sichuan PalmHeights Village'),
(109, 'Sichuan PalmVillage Village'),
(109, 'Sichuan PalmSprings Village'),
(109, 'Sichuan PalmCreek Village'),
(110, 'Sichuan RoseCreek Village'),
(110, 'Sichuan RoseTerrace Village'),
(110, 'Sichuan RoseCove Village'),
(110, 'Sichuan RoseWoodlands Village'),
(111, 'Sichuan CloverWoodlands Village'),
(111, 'Sichuan CloverPlains Village'),
(111, 'Sichuan CloverOrchard Village'),
(111, 'Sichuan CloverVale Village'),
(112, 'Sichuan MeadowVale Village'),
(112, 'Sichuan MeadowHarbour Village'),
(112, 'Sichuan MeadowGlade Village'),
(112, 'Sichuan MeadowDale Village'),
(113, 'Seoul CrystalDale Village'),
(113, 'Seoul CrystalHeath Village'),
(113, 'Seoul CrystalLanding Village'),
(113, 'Seoul CrystalCourt Village'),
(114, 'Seoul HarmonyCourt Village'),
(114, 'Seoul HarmonyBay Village'),
(114, 'Seoul HarmonyGrove Village'),
(114, 'Seoul HarmonyHeights Village'),
(115, 'Seoul BrightHeights Village'),
(115, 'Seoul BrightBrook Village'),
(115, 'Seoul BrightValley Village'),
(115, 'Seoul BrightFields Village'),
(116, 'Seoul MistyFields Village'),
(116, 'Seoul MistyHaven Village'),
(116, 'Seoul MistyRidge Village'),
(116, 'Seoul MistyPark Village'),
(117, 'Busan LakePark Village'),
(117, 'Busan LakeMeadows Village'),
(117, 'Busan LakePoint Village'),
(117, 'Busan LakeView Village'),
(118, 'Busan HillView Village'),
(118, 'Busan HillGardens Village'),
(118, 'Busan HillCrossing Village'),
(118, 'Busan HillEstate Village'),
(119, 'Busan ForestEstate Village'),
(119, 'Busan ForestHeights Village'),
(119, 'Busan ForestVillage Village'),
(119, 'Busan ForestSprings Village'),
(120, 'Busan GardenSprings Village'),
(120, 'Busan GardenCreek Village'),
(120, 'Busan GardenTerrace Village'),
(120, 'Busan GardenCove Village'),
(121, 'Incheon BlueCove Village'),
(121, 'Incheon BlueWoodlands Village'),
(121, 'Incheon BluePlains Village'),
(121, 'Incheon BlueOrchard Village'),
(122, 'Incheon GreenOrchard Village'),
(122, 'Incheon GreenVale Village'),
(122, 'Incheon GreenHarbour Village'),
(122, 'Incheon GreenGlade Village'),
(123, 'Incheon RedGlade Village'),
(123, 'Incheon RedDale Village'),
(123, 'Incheon RedHeath Village'),
(123, 'Incheon RedLanding Village'),
(124, 'Incheon SapphireLanding Village'),
(124, 'Incheon SapphireCourt Village'),
(124, 'Incheon SapphireBay Village'),
(124, 'Incheon SapphireGrove Village'),
(125, 'Daegu JadeGrove Village'),
(125, 'Daegu JadeHeights Village'),
(125, 'Daegu JadeBrook Village'),
(125, 'Daegu JadeValley Village'),
(126, 'Daegu CoralValley Village'),
(126, 'Daegu CoralFields Village'),
(126, 'Daegu CoralHaven Village'),
(126, 'Daegu CoralRidge Village'),
(127, 'Daegu MorningRidge Village'),
(127, 'Daegu MorningPark Village'),
(127, 'Daegu MorningMeadows Village'),
(127, 'Daegu MorningPoint Village'),
(128, 'Daegu GoldenleafPoint Village'),
(128, 'Daegu GoldenleafView Village'),
(128, 'Daegu GoldenleafGardens Village'),
(128, 'Daegu GoldenleafCrossing Village'),
(129, 'Bavaria AmberCrossing Village'),
(129, 'Bavaria AmberEstate Village'),
(129, 'Bavaria AmberHeights Village'),
(129, 'Bavaria AmberVillage Village'),
(130, 'Bavaria SilverVillage Village'),
(130, 'Bavaria SilverSprings Village'),
(130, 'Bavaria SilverCreek Village'),
(130, 'Bavaria SilverTerrace Village'),
(131, 'Bavaria GoldenTerrace Village'),
(131, 'Bavaria GoldenCove Village'),
(131, 'Bavaria GoldenWoodlands Village'),
(131, 'Bavaria GoldenPlains Village'),
(132, 'Bavaria EmeraldPlains Village'),
(132, 'Bavaria EmeraldOrchard Village'),
(132, 'Bavaria EmeraldVale Village'),
(132, 'Bavaria EmeraldHarbour Village'),
(133, 'Berlin MapleHarbour Village'),
(133, 'Berlin MapleGlade Village'),
(133, 'Berlin MapleDale Village'),
(133, 'Berlin MapleHeath Village'),
(134, 'Berlin WillowHeath Village'),
(134, 'Berlin WillowLanding Village'),
(134, 'Berlin WillowCourt Village'),
(134, 'Berlin WillowBay Village'),
(135, 'Berlin CedarBay Village'),
(135, 'Berlin CedarGrove Village'),
(135, 'Berlin CedarHeights Village'),
(135, 'Berlin CedarBrook Village'),
(136, 'Berlin PineBrook Village'),
(136, 'Berlin PineValley Village'),
(136, 'Berlin PineFields Village'),
(136, 'Berlin PineHaven Village'),
(137, 'Hesse RiverHaven Village'),
(137, 'Hesse RiverRidge Village'),
(137, 'Hesse RiverPark Village'),
(137, 'Hesse RiverMeadows Village'),
(138, 'Hesse SunnyMeadows Village'),
(138, 'Hesse SunnyPoint Village'),
(138, 'Hesse SunnyView Village'),
(138, 'Hesse SunnyGardens Village'),
(139, 'Hesse SpringGardens Village'),
(139, 'Hesse SpringCrossing Village'),
(139, 'Hesse SpringEstate Village'),
(139, 'Hesse SpringHeights Village'),
(140, 'Hesse OakHeights Village'),
(140, 'Hesse OakVillage Village'),
(140, 'Hesse OakSprings Village'),
(140, 'Hesse OakCreek Village'),
(141, 'Saxony PalmCreek Village'),
(141, 'Saxony PalmTerrace Village'),
(141, 'Saxony PalmCove Village'),
(141, 'Saxony PalmWoodlands Village'),
(142, 'Saxony RoseWoodlands Village'),
(142, 'Saxony RosePlains Village'),
(142, 'Saxony RoseOrchard Village'),
(142, 'Saxony RoseVale Village'),
(143, 'Saxony CloverVale Village'),
(143, 'Saxony CloverHarbour Village'),
(143, 'Saxony CloverGlade Village'),
(143, 'Saxony CloverDale Village'),
(144, 'Saxony MeadowDale Village'),
(144, 'Saxony MeadowHeath Village'),
(144, 'Saxony MeadowLanding Village'),
(144, 'Saxony MeadowCourt Village'),
(145, 'Paris CrystalCourt Village'),
(145, 'Paris CrystalBay Village'),
(145, 'Paris CrystalGrove Village'),
(145, 'Paris CrystalHeights Village'),
(146, 'Paris HarmonyHeights Village'),
(146, 'Paris HarmonyBrook Village'),
(146, 'Paris HarmonyValley Village'),
(146, 'Paris HarmonyFields Village'),
(147, 'Paris BrightFields Village'),
(147, 'Paris BrightHaven Village'),
(147, 'Paris BrightRidge Village'),
(147, 'Paris BrightPark Village'),
(148, 'Paris MistyPark Village'),
(148, 'Paris MistyMeadows Village'),
(148, 'Paris MistyPoint Village'),
(148, 'Paris MistyView Village'),
(149, 'Lyon LakeView Village'),
(149, 'Lyon LakeGardens Village'),
(149, 'Lyon LakeCrossing Village'),
(149, 'Lyon LakeEstate Village'),
(150, 'Lyon HillEstate Village'),
(150, 'Lyon HillHeights Village'),
(150, 'Lyon HillVillage Village'),
(150, 'Lyon HillSprings Village'),
(151, 'Lyon ForestSprings Village'),
(151, 'Lyon ForestCreek Village'),
(151, 'Lyon ForestTerrace Village'),
(151, 'Lyon ForestCove Village'),
(152, 'Lyon GardenCove Village'),
(152, 'Lyon GardenWoodlands Village'),
(152, 'Lyon GardenPlains Village'),
(152, 'Lyon GardenOrchard Village'),
(153, 'Marseille BlueOrchard Village'),
(153, 'Marseille BlueVale Village'),
(153, 'Marseille BlueHarbour Village'),
(153, 'Marseille BlueGlade Village'),
(154, 'Marseille GreenGlade Village'),
(154, 'Marseille GreenDale Village'),
(154, 'Marseille GreenHeath Village'),
(154, 'Marseille GreenLanding Village'),
(155, 'Marseille RedLanding Village'),
(155, 'Marseille RedCourt Village'),
(155, 'Marseille RedBay Village'),
(155, 'Marseille RedGrove Village'),
(156, 'Marseille SapphireGrove Village'),
(156, 'Marseille SapphireHeights Village'),
(156, 'Marseille SapphireBrook Village'),
(156, 'Marseille SapphireValley Village'),
(157, 'Bordeaux JadeValley Village'),
(157, 'Bordeaux JadeFields Village'),
(157, 'Bordeaux JadeHaven Village'),
(157, 'Bordeaux JadeRidge Village'),
(158, 'Bordeaux CoralRidge Village'),
(158, 'Bordeaux CoralPark Village'),
(158, 'Bordeaux CoralMeadows Village'),
(158, 'Bordeaux CoralPoint Village'),
(159, 'Bordeaux MorningPoint Village'),
(159, 'Bordeaux MorningView Village'),
(159, 'Bordeaux MorningGardens Village'),
(159, 'Bordeaux MorningCrossing Village'),
(160, 'Bordeaux GoldenleafCrossing Village'),
(160, 'Bordeaux GoldenleafEstate Village'),
(160, 'Bordeaux GoldenleafHeights Village'),
(160, 'Bordeaux GoldenleafVillage Village'),
(161, 'Rome AmberVillage Village'),
(161, 'Rome AmberSprings Village'),
(161, 'Rome AmberCreek Village'),
(161, 'Rome AmberTerrace Village'),
(162, 'Rome SilverTerrace Village'),
(162, 'Rome SilverCove Village'),
(162, 'Rome SilverWoodlands Village'),
(162, 'Rome SilverPlains Village'),
(163, 'Rome GoldenPlains Village'),
(163, 'Rome GoldenOrchard Village'),
(163, 'Rome GoldenVale Village'),
(163, 'Rome GoldenHarbour Village'),
(164, 'Rome EmeraldHarbour Village'),
(164, 'Rome EmeraldGlade Village'),
(164, 'Rome EmeraldDale Village'),
(164, 'Rome EmeraldHeath Village'),
(165, 'Milan MapleHeath Village'),
(165, 'Milan MapleLanding Village'),
(165, 'Milan MapleCourt Village'),
(165, 'Milan MapleBay Village'),
(166, 'Milan WillowBay Village'),
(166, 'Milan WillowGrove Village'),
(166, 'Milan WillowHeights Village'),
(166, 'Milan WillowBrook Village'),
(167, 'Milan CedarBrook Village'),
(167, 'Milan CedarValley Village'),
(167, 'Milan CedarFields Village'),
(167, 'Milan CedarHaven Village'),
(168, 'Milan PineHaven Village'),
(168, 'Milan PineRidge Village'),
(168, 'Milan PinePark Village'),
(168, 'Milan PineMeadows Village'),
(169, 'Naples RiverMeadows Village'),
(169, 'Naples RiverPoint Village'),
(169, 'Naples RiverView Village'),
(169, 'Naples RiverGardens Village'),
(170, 'Naples SunnyGardens Village'),
(170, 'Naples SunnyCrossing Village'),
(170, 'Naples SunnyEstate Village'),
(170, 'Naples SunnyHeights Village'),
(171, 'Naples SpringHeights Village'),
(171, 'Naples SpringVillage Village'),
(171, 'Naples SpringSprings Village'),
(171, 'Naples SpringCreek Village'),
(172, 'Naples OakCreek Village'),
(172, 'Naples OakTerrace Village'),
(172, 'Naples OakCove Village'),
(172, 'Naples OakWoodlands Village'),
(173, 'Turin PalmWoodlands Village'),
(173, 'Turin PalmPlains Village'),
(173, 'Turin PalmOrchard Village'),
(173, 'Turin PalmVale Village'),
(174, 'Turin RoseVale Village'),
(174, 'Turin RoseHarbour Village'),
(174, 'Turin RoseGlade Village'),
(174, 'Turin RoseDale Village'),
(175, 'Turin CloverDale Village'),
(175, 'Turin CloverHeath Village'),
(175, 'Turin CloverLanding Village'),
(175, 'Turin CloverCourt Village'),
(176, 'Turin MeadowCourt Village'),
(176, 'Turin MeadowBay Village'),
(176, 'Turin MeadowGrove Village'),
(176, 'Turin MeadowHeights Village'),
(177, 'Madrid CrystalHeights Village'),
(177, 'Madrid CrystalBrook Village'),
(177, 'Madrid CrystalValley Village'),
(177, 'Madrid CrystalFields Village'),
(178, 'Madrid HarmonyFields Village'),
(178, 'Madrid HarmonyHaven Village'),
(178, 'Madrid HarmonyRidge Village'),
(178, 'Madrid HarmonyPark Village'),
(179, 'Madrid BrightPark Village'),
(179, 'Madrid BrightMeadows Village'),
(179, 'Madrid BrightPoint Village'),
(179, 'Madrid BrightView Village'),
(180, 'Madrid MistyView Village'),
(180, 'Madrid MistyGardens Village'),
(180, 'Madrid MistyCrossing Village'),
(180, 'Madrid MistyEstate Village'),
(181, 'Barcelona LakeEstate Village'),
(181, 'Barcelona LakeHeights Village'),
(181, 'Barcelona LakeVillage Village'),
(181, 'Barcelona LakeSprings Village'),
(182, 'Barcelona HillSprings Village'),
(182, 'Barcelona HillCreek Village'),
(182, 'Barcelona HillTerrace Village'),
(182, 'Barcelona HillCove Village'),
(183, 'Barcelona ForestCove Village'),
(183, 'Barcelona ForestWoodlands Village'),
(183, 'Barcelona ForestPlains Village'),
(183, 'Barcelona ForestOrchard Village'),
(184, 'Barcelona GardenOrchard Village'),
(184, 'Barcelona GardenVale Village'),
(184, 'Barcelona GardenHarbour Village'),
(184, 'Barcelona GardenGlade Village'),
(185, 'Valencia BlueGlade Village'),
(185, 'Valencia BlueDale Village'),
(185, 'Valencia BlueHeath Village'),
(185, 'Valencia BlueLanding Village'),
(186, 'Valencia GreenLanding Village'),
(186, 'Valencia GreenCourt Village'),
(186, 'Valencia GreenBay Village'),
(186, 'Valencia GreenGrove Village'),
(187, 'Valencia RedGrove Village'),
(187, 'Valencia RedHeights Village'),
(187, 'Valencia RedBrook Village'),
(187, 'Valencia RedValley Village'),
(188, 'Valencia SapphireValley Village'),
(188, 'Valencia SapphireFields Village'),
(188, 'Valencia SapphireHaven Village'),
(188, 'Valencia SapphireRidge Village'),
(189, 'Seville JadeRidge Village'),
(189, 'Seville JadePark Village'),
(189, 'Seville JadeMeadows Village'),
(189, 'Seville JadePoint Village'),
(190, 'Seville CoralPoint Village'),
(190, 'Seville CoralView Village'),
(190, 'Seville CoralGardens Village'),
(190, 'Seville CoralCrossing Village'),
(191, 'Seville MorningCrossing Village'),
(191, 'Seville MorningEstate Village'),
(191, 'Seville MorningHeights Village'),
(191, 'Seville MorningVillage Village'),
(192, 'Seville GoldenleafVillage Village'),
(192, 'Seville GoldenleafSprings Village'),
(192, 'Seville GoldenleafCreek Village'),
(192, 'Seville GoldenleafTerrace Village'),
(193, 'California AmberTerrace Village'),
(193, 'California AmberCove Village'),
(193, 'California AmberWoodlands Village'),
(193, 'California AmberPlains Village'),
(194, 'California SilverPlains Village'),
(194, 'California SilverOrchard Village'),
(194, 'California SilverVale Village'),
(194, 'California SilverHarbour Village'),
(195, 'California GoldenHarbour Village'),
(195, 'California GoldenGlade Village'),
(195, 'California GoldenDale Village'),
(195, 'California GoldenHeath Village'),
(196, 'California EmeraldHeath Village'),
(196, 'California EmeraldLanding Village'),
(196, 'California EmeraldCourt Village'),
(196, 'California EmeraldBay Village'),
(197, 'Texas MapleBay Village'),
(197, 'Texas MapleGrove Village'),
(197, 'Texas MapleHeights Village'),
(197, 'Texas MapleBrook Village'),
(198, 'Texas WillowBrook Village'),
(198, 'Texas WillowValley Village'),
(198, 'Texas WillowFields Village'),
(198, 'Texas WillowHaven Village'),
(199, 'Texas CedarHaven Village'),
(199, 'Texas CedarRidge Village'),
(199, 'Texas CedarPark Village'),
(199, 'Texas CedarMeadows Village'),
(200, 'Texas PineMeadows Village'),
(200, 'Texas PinePoint Village'),
(200, 'Texas PineView Village'),
(200, 'Texas PineGardens Village'),
(201, 'Florida RiverGardens Village'),
(201, 'Florida RiverCrossing Village'),
(201, 'Florida RiverEstate Village'),
(201, 'Florida RiverHeights Village'),
(202, 'Florida SunnyHeights Village'),
(202, 'Florida SunnyVillage Village'),
(202, 'Florida SunnySprings Village'),
(202, 'Florida SunnyCreek Village'),
(203, 'Florida SpringCreek Village'),
(203, 'Florida SpringTerrace Village'),
(203, 'Florida SpringCove Village'),
(203, 'Florida SpringWoodlands Village'),
(204, 'Florida OakWoodlands Village'),
(204, 'Florida OakPlains Village'),
(204, 'Florida OakOrchard Village'),
(204, 'Florida OakVale Village'),
(205, 'New York PalmVale Village'),
(205, 'New York PalmHarbour Village'),
(205, 'New York PalmGlade Village'),
(205, 'New York PalmDale Village'),
(206, 'New York RoseDale Village'),
(206, 'New York RoseHeath Village'),
(206, 'New York RoseLanding Village'),
(206, 'New York RoseCourt Village'),
(207, 'New York CloverCourt Village'),
(207, 'New York CloverBay Village'),
(207, 'New York CloverGrove Village'),
(207, 'New York CloverHeights Village'),
(208, 'New York MeadowHeights Village'),
(208, 'New York MeadowBrook Village'),
(208, 'New York MeadowValley Village'),
(208, 'New York MeadowFields Village'),
(209, 'Ontario CrystalFields Village'),
(209, 'Ontario CrystalHaven Village'),
(209, 'Ontario CrystalRidge Village'),
(209, 'Ontario CrystalPark Village'),
(210, 'Ontario HarmonyPark Village'),
(210, 'Ontario HarmonyMeadows Village'),
(210, 'Ontario HarmonyPoint Village'),
(210, 'Ontario HarmonyView Village'),
(211, 'Ontario BrightView Village'),
(211, 'Ontario BrightGardens Village'),
(211, 'Ontario BrightCrossing Village'),
(211, 'Ontario BrightEstate Village'),
(212, 'Ontario MistyEstate Village'),
(212, 'Ontario MistyHeights Village'),
(212, 'Ontario MistyVillage Village'),
(212, 'Ontario MistySprings Village'),
(213, 'Quebec LakeSprings Village'),
(213, 'Quebec LakeCreek Village'),
(213, 'Quebec LakeTerrace Village'),
(213, 'Quebec LakeCove Village'),
(214, 'Quebec HillCove Village'),
(214, 'Quebec HillWoodlands Village'),
(214, 'Quebec HillPlains Village'),
(214, 'Quebec HillOrchard Village'),
(215, 'Quebec ForestOrchard Village'),
(215, 'Quebec ForestVale Village'),
(215, 'Quebec ForestHarbour Village'),
(215, 'Quebec ForestGlade Village'),
(216, 'Quebec GardenGlade Village'),
(216, 'Quebec GardenDale Village'),
(216, 'Quebec GardenHeath Village'),
(216, 'Quebec GardenLanding Village'),
(217, 'Alberta BlueLanding Village'),
(217, 'Alberta BlueCourt Village'),
(217, 'Alberta BlueBay Village'),
(217, 'Alberta BlueGrove Village'),
(218, 'Alberta GreenGrove Village'),
(218, 'Alberta GreenHeights Village'),
(218, 'Alberta GreenBrook Village'),
(218, 'Alberta GreenValley Village'),
(219, 'Alberta RedValley Village'),
(219, 'Alberta RedFields Village'),
(219, 'Alberta RedHaven Village'),
(219, 'Alberta RedRidge Village'),
(220, 'Alberta SapphireRidge Village'),
(220, 'Alberta SapphirePark Village'),
(220, 'Alberta SapphireMeadows Village'),
(220, 'Alberta SapphirePoint Village'),
(221, 'British Columbia JadePoint Village'),
(221, 'British Columbia JadeView Village'),
(221, 'British Columbia JadeGardens Village'),
(221, 'British Columbia JadeCrossing Village'),
(222, 'British Columbia CoralCrossing Village'),
(222, 'British Columbia CoralEstate Village'),
(222, 'British Columbia CoralHeights Village'),
(222, 'British Columbia CoralVillage Village'),
(223, 'British Columbia MorningVillage Village'),
(223, 'British Columbia MorningSprings Village'),
(223, 'British Columbia MorningCreek Village'),
(223, 'British Columbia MorningTerrace Village'),
(224, 'British Columbia GoldenleafTerrace Village'),
(224, 'British Columbia GoldenleafCove Village'),
(224, 'British Columbia GoldenleafWoodlands Village'),
(224, 'British Columbia GoldenleafPlains Village'),
(225, 'Mexico City AmberPlains Village'),
(225, 'Mexico City AmberOrchard Village'),
(225, 'Mexico City AmberVale Village'),
(225, 'Mexico City AmberHarbour Village'),
(226, 'Mexico City SilverHarbour Village'),
(226, 'Mexico City SilverGlade Village'),
(226, 'Mexico City SilverDale Village'),
(226, 'Mexico City SilverHeath Village'),
(227, 'Mexico City GoldenHeath Village'),
(227, 'Mexico City GoldenLanding Village'),
(227, 'Mexico City GoldenCourt Village'),
(227, 'Mexico City GoldenBay Village'),
(228, 'Mexico City EmeraldBay Village'),
(228, 'Mexico City EmeraldGrove Village'),
(228, 'Mexico City EmeraldHeights Village'),
(228, 'Mexico City EmeraldBrook Village'),
(229, 'Jalisco MapleBrook Village'),
(229, 'Jalisco MapleValley Village'),
(229, 'Jalisco MapleFields Village'),
(229, 'Jalisco MapleHaven Village'),
(230, 'Jalisco WillowHaven Village'),
(230, 'Jalisco WillowRidge Village'),
(230, 'Jalisco WillowPark Village'),
(230, 'Jalisco WillowMeadows Village'),
(231, 'Jalisco CedarMeadows Village'),
(231, 'Jalisco CedarPoint Village'),
(231, 'Jalisco CedarView Village'),
(231, 'Jalisco CedarGardens Village'),
(232, 'Jalisco PineGardens Village'),
(232, 'Jalisco PineCrossing Village'),
(232, 'Jalisco PineEstate Village'),
(232, 'Jalisco PineHeights Village'),
(233, 'Nuevo Leon RiverHeights Village'),
(233, 'Nuevo Leon RiverVillage Village'),
(233, 'Nuevo Leon RiverSprings Village'),
(233, 'Nuevo Leon RiverCreek Village'),
(234, 'Nuevo Leon SunnyCreek Village'),
(234, 'Nuevo Leon SunnyTerrace Village'),
(234, 'Nuevo Leon SunnyCove Village'),
(234, 'Nuevo Leon SunnyWoodlands Village'),
(235, 'Nuevo Leon SpringWoodlands Village'),
(235, 'Nuevo Leon SpringPlains Village'),
(235, 'Nuevo Leon SpringOrchard Village'),
(235, 'Nuevo Leon SpringVale Village'),
(236, 'Nuevo Leon OakVale Village'),
(236, 'Nuevo Leon OakHarbour Village'),
(236, 'Nuevo Leon OakGlade Village'),
(236, 'Nuevo Leon OakDale Village'),
(237, 'Yucatan PalmDale Village'),
(237, 'Yucatan PalmHeath Village'),
(237, 'Yucatan PalmLanding Village'),
(237, 'Yucatan PalmCourt Village'),
(238, 'Yucatan RoseCourt Village'),
(238, 'Yucatan RoseBay Village'),
(238, 'Yucatan RoseGrove Village'),
(238, 'Yucatan RoseHeights Village'),
(239, 'Yucatan CloverHeights Village'),
(239, 'Yucatan CloverBrook Village'),
(239, 'Yucatan CloverValley Village'),
(239, 'Yucatan CloverFields Village'),
(240, 'Yucatan MeadowFields Village'),
(240, 'Yucatan MeadowHaven Village'),
(240, 'Yucatan MeadowRidge Village'),
(240, 'Yucatan MeadowPark Village'),
(241, 'Havana CrystalPark Village'),
(241, 'Havana CrystalMeadows Village'),
(241, 'Havana CrystalPoint Village'),
(241, 'Havana CrystalView Village'),
(242, 'Havana HarmonyView Village'),
(242, 'Havana HarmonyGardens Village'),
(242, 'Havana HarmonyCrossing Village'),
(242, 'Havana HarmonyEstate Village'),
(243, 'Havana BrightEstate Village'),
(243, 'Havana BrightHeights Village'),
(243, 'Havana BrightVillage Village'),
(243, 'Havana BrightSprings Village'),
(244, 'Havana MistySprings Village'),
(244, 'Havana MistyCreek Village'),
(244, 'Havana MistyTerrace Village'),
(244, 'Havana MistyCove Village'),
(245, 'Santiago LakeCove Village'),
(245, 'Santiago LakeWoodlands Village'),
(245, 'Santiago LakePlains Village'),
(245, 'Santiago LakeOrchard Village'),
(246, 'Santiago HillOrchard Village'),
(246, 'Santiago HillVale Village'),
(246, 'Santiago HillHarbour Village'),
(246, 'Santiago HillGlade Village'),
(247, 'Santiago ForestGlade Village'),
(247, 'Santiago ForestDale Village'),
(247, 'Santiago ForestHeath Village'),
(247, 'Santiago ForestLanding Village'),
(248, 'Santiago GardenLanding Village'),
(248, 'Santiago GardenCourt Village'),
(248, 'Santiago GardenBay Village'),
(248, 'Santiago GardenGrove Village'),
(249, 'Camaguey BlueGrove Village'),
(249, 'Camaguey BlueHeights Village'),
(249, 'Camaguey BlueBrook Village'),
(249, 'Camaguey BlueValley Village'),
(250, 'Camaguey GreenValley Village'),
(250, 'Camaguey GreenFields Village'),
(250, 'Camaguey GreenHaven Village'),
(250, 'Camaguey GreenRidge Village'),
(251, 'Camaguey RedRidge Village'),
(251, 'Camaguey RedPark Village'),
(251, 'Camaguey RedMeadows Village'),
(251, 'Camaguey RedPoint Village'),
(252, 'Camaguey SapphirePoint Village'),
(252, 'Camaguey SapphireView Village'),
(252, 'Camaguey SapphireGardens Village'),
(252, 'Camaguey SapphireCrossing Village'),
(253, 'Holguin JadeCrossing Village'),
(253, 'Holguin JadeEstate Village'),
(253, 'Holguin JadeHeights Village'),
(253, 'Holguin JadeVillage Village'),
(254, 'Holguin CoralVillage Village'),
(254, 'Holguin CoralSprings Village'),
(254, 'Holguin CoralCreek Village'),
(254, 'Holguin CoralTerrace Village'),
(255, 'Holguin MorningTerrace Village'),
(255, 'Holguin MorningCove Village'),
(255, 'Holguin MorningWoodlands Village'),
(255, 'Holguin MorningPlains Village'),
(256, 'Holguin GoldenleafPlains Village'),
(256, 'Holguin GoldenleafOrchard Village'),
(256, 'Holguin GoldenleafVale Village'),
(256, 'Holguin GoldenleafHarbour Village');
